import { getServices } from "@/assets/services";

export const services = [
  {
    id: 1,
    price: 40,
    time: 40,
    checked: true,
    name: "Beard & hair",
    icon: getServices("beard_hair"),
  },
  {
    id: 2,
    time: 40,
    price: 35,
    checked: false,
    name: "Beard",
    icon: getServices("beard"),
  },
  {
    id: 3,
    time: 40,
    price: 25,
    checked: false,
    name: "Hair",
    icon: getServices("electric_razor_cut"),
  },
  {
    id: 4,
    time: 40,
    price: 28,
    checked: false,
    name: "Scissor Cut",
    icon: getServices("scissor_cut"),
  },
  {
    id: 5,
    time: 40,
    price: 35,
    checked: false,
    name: "Reflex",
    icon: getServices("reflex"),
  },
  {
    id: 6,
    time: 40,
    price: 40,
    checked: false,
    name: "Pigmentation",
    icon: getServices("pigmentation"),
  },
  {
    id: 7,
    time: 40,
    price: 40,
    checked: false,
    name: "Kids' cuts",
    icon: getServices("kids_cuts"),
  },
  {
    id: 8,
    time: 40,
    price: 8,
    checked: false,
    name: "Hair cuts",
    icon: getServices("haircuts"),
  },
  {
    id: 9,
    time: 40,
    price: 8,
    checked: false,
    name: "Eyebrow",
    icon: getServices("eyebrow"),
  },
];
