import { getImage } from "@/assets/images";
import { getServices } from "@/assets/services";

export const promotionsWeek = [
  {
    id: 1,
    price: 40,
    name: "Beard & hair",
    icon: getServices("beard_hair"),
  },
  {
    id: 2,
    price: 35,
    name: "Beard",
    icon: getServices("beard"),
  },
  {
    id: 3,
    price: 25,
    name: "Hair",
    icon: getServices("electric_razor_cut"),
  },
  {
    id: 4,
    price: 28,
    name: "Scissor Cut",
    icon: getServices("scissor_cut"),
  },
  {
    id: 5,
    price: 35,
    name: "Reflex",
    icon: getServices("reflex"),
  },
  {
    id: 6,
    price: 40,
    name: "Pigmentation",
    icon: getServices("pigmentation"),
  },
  {
    id: 7,
    price: 40,
    name: "Kids' cuts",
    icon: getServices("kids_cuts"),
  },
  {
    id: 8,
    price: 8,
    name: "Hair cuts",
    icon: getServices("haircuts"),
  },
  {
    id: 9,
    price: 8,
    name: "Eyebrow",
    icon: getServices("eyebrow"),
  },
];

export const orders = [
  {
    id: 1,
    time: 40,
    name: "Beard & hair",
    barber: "Breno Tavares", 
    icon: getServices("beard_hair"),
    location: "Barbearia faz milagres",
  },
  {
    id: 2,
    time: 20,
    name: "Beard",
    barber: "Breno Tavares", 
    icon: getServices("beard"),
    location: "Barbearia faz milagres",
  },
  {
    id: 3,
    time: 25,
    name: "Hair",
    barber: "Breno Tavares", 
    icon: getServices("electric_razor_cut"),
    location: "Barbearia faz milagres",
  },
  {
    id: 4,
    time: 28,
    name: "Scissor Cut",
    barber: "Jaja", 
    icon: getServices("scissor_cut"),
    location: "Barbearia faz milagres",
  },
  {
    id: 5,
    time: 35,
    name: "Reflex",
    barber: "Breno Tavares", 
    icon: getServices("reflex"),
    location: "Barbearia faz milagres",
  },
  {
    id: 6,
    time: 40,
    name: "Pigmentation",
    barber: "Angelo Lima", 
    icon: getServices("pigmentation"),
    location: "Barbearia faz milagres",
  },
  {
    id: 7,
    time: 40,
    name: "Kids' cuts",
    barber: "Joao Pedro", 
    icon: getServices("kids_cuts"),
    location: "Barbearia faz milagres",
  },
  {
    id: 8,
    time: 8,
    name: "Hair cuts",
    barber: "Danyel Coelho", 
    icon: getServices("haircuts"),
    location: "Barbearia faz milagres",
  },
  {
    id: 9,
    time: 8,
    name: "Eyebrow",
    barber: "Breno Tavares", 
    icon: getServices("eyebrow"),
    location: "Barbearia faz milagres",
  },
];

export const barbers = [
  {
    id: 1,
    cuts: 1872,
    rating: 4.8,
    type: "Barbeiro",
    name: "Willian",
    image: getImage("willian"),
    location: "Barbearia faz milagres",
  },
  {
    id: 2,
    cuts: 1872,
    rating: 4.8,
    type: "Barbeiro",
    name: "Breno Tavares",
    image: getImage("breno_tavares"),
    location: "Barbearia faz milagres",
  },
  {
    id: 3,
    cuts: 1872,
    rating: 4.8,
    type: "Barbeiro",
    name: "Angelo lima",
    image: getImage("angelo_lima"),
    location: "Barbearia faz milagres",
  },
  {
    id: 4,
    cuts: 1872,
    rating: 4.8,
    type: "Barbeiro",
    name: "Danyel coelho",
    image: getImage("danyel_coelho"),
    location: "Barbearia faz milagres",
  },
  {
    id: 5,
    cuts: 1872,
    rating: 4.8,
    type: "Barbeiro",
    name: "Joao pedro",
    image: getImage("joao_pedro"),
    location: "Barbearia faz milagres",
  },
  {
    id: 6,
    cuts: 1872,
    rating: 4.8,
    type: "Barbeiro",
    name: "Jaja",
    image: getImage("Jaja"),
    location: "Barbearia faz milagres",
  },
];
